import './js/js.js';
import './js/js2.js';
import './scss/base.scss';
import './scss/typography.scss';
import './scss/nav.scss';
import './scss/main-section.scss';
import './scss/page-wrapper.scss';
import './scss/payment-heading.scss';
import './scss/footer.scss';